theme: jekyll-theme-midnight
title: Welcome to NotHerAgain's homepage. 
description: Feel free to save this page to see all the cool things I get up to!

# Welcome to my portfolio!

You can find my work on [codepen](https://codepen.io/NotHerAgain/) and [github](https://github.com/NotHerAgain).

You can see all the random things I do with coding on [Twitter](https://twitter.com/NotHerAgain3)


## **About Me**

I'm learning coding at home whilst still locked away whilst the world goes a little bit crazy outside.
I've been in education for far too long, and I need a break... for now!


### Things I like _more_ than computers!
- Microbes!
- Medical History!
- Crochet!
- Knitting!
- Cake!
- Crafts!
- Glitter!


